CREATE DATABASE [MarketPlaceServiceAPI];

USE MarketPlaceServiceAPI;

CREATE TABLE dbo.[Category](
	Category_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50)
);

CREATE TABLE dbo.[Market](
	Market_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50)
);

CREATE TABLE dbo.[Discount](
	Discount_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Offer_as_percent FLOAT(10)
);


CREATE TABLE dbo.[Product](
	Product_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Price FLOAT(10) NOT NULL,
	Category_id INT NOT NULL,
	Market_id INT NOT NULL,
	Discount_id INT NOT NULL,
	Picture_id VARCHAR(100),
	CONSTRAINT FK_CATEGORY FOREIGN KEY(Category_id)
		REFERENCES dbo.[Category]
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_MARKET FOREIGN KEY(Market_id)
		REFERENCES dbo.[Market]
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_DISCOUNT FOREIGN KEY(Discount_id)
		REFERENCES dbo.[Discount]
		ON DELETE CASCADE
		ON UPDATE CASCADE,
);